### ISSUE TITLE
Get dev/staging/prod servers from Ops

### ISSUE THREAD

**Issue by readevalprint** [eHealthAfrica/trace-and-go#45]
We need AWS instances and databases. Did we decide on a subdomain?

**Comment by lucychambers** [comment]
@readevalprint search your Slack chat for: "dev-trace-and-go.eocng.org" (messages from April 29th, I believe this refers in part to what @tremolo did for us, but not sure if he has already done everything you need). 

This is also related to: [#28](https://github.com/eHealthAfrica/trace-and-go/issues/28). 

Please let me know asap anything else we need from DevOps this week and I'll make sure it comes up at sprint planning meeting!

**Comment by readevalprint** [comment]
Ok great, that covers dev, but we will need the same for staging and prod server. Not a super emergency at this moment. But within the next couple weeks.

**Comment by lucychambers** [comment]
Fab. 

Just so I understand, there is already a production instance of TAG. However, we are going for a slightly different setup, in terms of database etc so we will need a new production instance. Trying to understand what will happen to the original production instance. 

I'm just trying to work out if I need to give people a headsup that things will stop working / freeze at: http://etu-demo.ebolaeoc.org/ at some point, so that I can manage the transition!

**Comment by readevalprint** [comment]
So at some point, we will redirect the etu-demo.ebolaeoc.org domain to the real production environment. And the data should be migrated as well right before. So best case scenario there is little to no downtime.

**Comment by readevalprint** [comment]
https://github.com/eHealthAfrica/ehealth-deployment/issues/233

**Comment by tremolo** [comment]
the servers and the RDS databases are set up, please use:
ubuntu@tag-a.ie.trace-and-go.eocng.org (= prod)
ubuntu@tag-b.ie.trace-and-go.eocng.org (= stage)
ubuntu@tag-c.ie.trace-and-go.eocng.org (= dev)
the database credentials are in the file db_credentials.txt on each of these servers.
Closing the ticket for now, if further setup is needed reopen or create new ticket.
